brands = [
    "adidas",
    "ASICS",
    "Avengers",
    "B52 by Bullboxer",
    "Baretraps",
    "Bates",
    "Batman",
    "BCBG",
    "Bearpaw",
    "Billabong",
    "Birkenstock",
    "Blowfish Malibu",
    "Blues Clues",
    "b.o.c",
    "Body Glove",
    "Bogs",
    "Brooks",
    "BullBoxer",
    "Bzees",
    "Carhartt",
    "Cars",
    "Carters",
    "Caterpillar",
    "Chaco",
    "Champion",
    "Circus NY",
    "Clarks",
    "Cliffs by White Mountain",
    "CoComelon",
    "Coconuts",
    "Cole Haan",
    "Columbia",
    "Converse",
    "Cool Planet by Steve Madden",
    "Crevo",
    "Crocs",
    "Dansko",
    "DC Shoes",
    "Deer Stags",
    "Disney Princess",
    "Dockers",
    "Dr. Martens",
    "Dr. Scholl's",
    "Dr. Scholl's Orig Collection",
    "Dr. Scholl's Work",
    "DV Dolce Vita",
    "Earth Origins",
    "Eastland",
    "Easy Street",
    "Easy Works by Easy Street",
    "Encanto",
    "Eurosoft",
    "FILA",
    "Florsheim",
    "Franco Sarto",
    "Frozen",
    "GUESS",
    "Harley Davidson",
    "Heelys",
    "HEYDUDE",
    "Highpoint",
    "Hunter Boot",
    "Impo",
    "Jambu",
    "JBU",
    "Jellypop",
    "JoJo Siwa",
    "Journee Collection",
    "JSport",
    "Jurassic World",
    "Kamik",
    "Keds",
    "KEEN",
    "Kenneth Cole New York",
    "Kenneth Cole Reaction",
    "Kenneth Cole Unlisted",
    "Kensie",
    "Khombu",
    "Koolaburra by UGG",
    "KORKS",
    "K-Swiss",
    "Levi's",
    "LifeStride",
    "Lightyear",
    "Lugz",
    "Madden",
    "Madden Girl",
    "Margaritaville",
    "Merrell",
    "MIA",
    "Mickey Mouse",
    "Minnetonka Moccasin",
    "Minnie Mouse",
    "Muk Luks",
    "Native Shoes",
    "Natural Soul",
    "Naturalizer",
    "New Balance",
    "Nike",
    "Nunn Bush",
    "OOFOS",
    "OshKosh B'gosh",
    "PALLADIUM",
    "Patrizia",
    "Paw Patrol",
    "Perry Ellis Portfolio",
    "Propet",
    "PUMA",
    "Rachel Shoes",
    "Reebok",
    "Reebok Duty",
    "Reebok Work",
    "Reef",
    "Rider",
    "Rockport",
    "Rockport Works",
    "Roxy",
    "Rykä",
    "Sam Edelman",
    "Sanuk",
    "Sarto by Franco Sarto",
    "Saucony",
    "Skechers",
    "Skechers Work",
    "Sof Sole",
    "SOUL Naturalizer",
    "Space Jam",
    "Sperry",
    "Spider-Man",
    "Sporto",
    "Spring Step",
    "Sprox",
    "Stacy Adams",
    "Steve Madden",
    "Stride Rite",
    "Territory",
    "Teva",
    "Thomas & Vine",
    "Timberland",
    "Timberland Pro",
    "Tommy Hilfiger",
    "Touch of Nina",
    "Toy Story",
    "Tretorn",
    "Under Armour",
    "Vance Co.",
    "Vans",
    "Vionic",
    "White Mountain",
    "Wolverine",
    "XOXO",
    "Zodiac"
]

colors = {
    "Red": "#FF0000",
    "Indian Red": "#CD5C5C",
    "Light Coral": "#F08080",
    "Salmon": "#FA8072",
    "Dark Salmon": "#E9967A",
    "Crimson": "#DC143C",
    "Fire Brick": "#B22222",
    "Dark Red": "#8B0000",
    "Pink": "#FFC0CB",
    "Light Pink": "#FFB6C1",
    "Hot Pink": "#FF69B4",
    "Deep Pink": "#FF1493",
    "Medium Violet Red": "#C71585",
    "Pale Violet Red": "#DB7093",
    "Orange": "#FFA500",
    "Light Salmon": "#FFA07A",
    "Coral": "#FF7F50",
    "Tomato": "#FF6347",
    "Orange Red": "#FF4500",
    "Dark Orange": "#FF8C00",
    "Yellow": "#FFFF00",
    "Gold": "#FFD700",
    "Light Yellow": "#FFFFE0",
    "Lemon Chiffon": "#FFFACD",
    "Light Goldenrod Yellow": "#FAFAD2",
    "Papaya Whip": "#FFEFD5",
    "Moccasin": "#FFE4B5",
    "Peach Puff": "#FFDAB9",
    "Pale Goldenrod": "#EEE8AA",
    "Khaki": "#F0E68C",
    "Dark Khaki": "#BDB76B",
    "Purple": "#800080",
    "Lavender": "#E6E6FA",
    "Thistle": "#D8BFD8",
    "Plum": "#DDA0DD",
    "Violet": "#EE82EE",
    "Orchid": "#DA70D6",
    "Fuchsia": "#FF00FF",
    "Magenta": "#FF00FF",
    "Medium Orchid": "#BA55D3",
    "Medium Purple": "#9370DB",
    "Rebecca Purple": "#663399",
    "Blue Violet": "#8A2BE2",
    "Dark Violet": "#9400D3",
    "Dark Orchid": "#9932CC",
    "Dark Magenta": "#8B008B",
    "Indigo": "#4B0082",
    "Slate Blue": "#6A5ACD",
    "Dark Slate Blue": "#483D8B",
    "Green": "#008000",
    "Green Yellow": "#ADFF2F",
    "Chartreuse": "#7FFF00",
    "Lawn Green": "#7CFC00",
    "Lime": "#00FF00",
    "Lime Green": "#32CD32",
    "Pale Green": "#98FB98",
    "Light Green": "#90EE90",
    "Medium Spring Green": "#00FA9A",
    "Spring Green": "#00FF7F",
    "Medium Sea Green": "#3CB371",
    "Sea Green": "#2E8B57",
    "Forest Green": "#228B22",
    "Dark Green": "#006400",
    "Yellow Green": "#9ACD32",
    "Olive Drab": "#6B8E23",
    "Olive": "#808000",
    "Dark Olive Green": "#556B2F",
    "Medium Aquamarine": "#66CDAA",
    "Dark Sea Green": "#8FBC8B",
    "Light Sea Green": "#20B2AA",
    "Dark Cyan": "#008B8B",
    "Teal": "#008080",
    "Blue": "#0000FF",
    "Aqua": "#00FFFF",
    "Cyan": "#00FFFF",
    "Light Cyan": "#E0FFFF",
    "Pale Turquoise": "#AFEEEE",
    "Aquamarine": "#7FFFD4",
    "Turquoise": "#40E0D0",
    "Medium Turquoise": "#48D1CC",
    "Dark Turquoise": "#00CED1",
    "Cadet Blue": "#5F9EA0",
    "Steel Blue": "#4682B4",
    "Light Steel Blue": "#B0C4DE",
    "Powder Blue": "#B0E0E6",
    "Light Blue": "#ADD8E6",
    "Sky Blue": "#87CEEB",
    "Light Sky Blue": "#87CEFA",
    "Deep Sky Blue": "#00BFFF",
    "Dodger Blue": "#1E90FF",
    "Cornflower Blue": "#6495ED",
    "Medium Slate Blue": "#7B68EE",
    "Royal Blue": "#4169E1",
    "Medium Blue": "#0000CD",
    "Dark Blue": "#00008B",
    "Navy": "#000080",
    "Midnight Blue": "#191970",
    "Brown": "#A52A2A",
    "Cornsilk": "#FFF8DC",
    "Blanched Almond": "#FFEBCD",
    "Bisque": "#FFE4C4",
    "Navajo White": "#FFDEAD",
    "Wheat": "#F5DEB3",
    "Burly Wood": "#DEB887",
    "Tan": "#D2B48C",
    "Rosy Brown": "#BC8F8F",
    "Sandy Brown": "#F4A460",
    "Goldenrod": "#DAA520",
    "Dark Goldenrod": "#B8860B",
    "Peru": "#CD853F",
    "Chocolate": "#D2691E",
    "Saddle Brown": "#8B4513",
    "Sienna": "#A0522D",
    "Maroon": "#800000",
    "White": "#FFFFFF",
    "Beige": "#F5F5DC",
    "Snow": "#FFFAFA",
    "Honey Dew": "#F0FFF0",
    "Mint Cream": "#F5FFFA",
    "Azure": "#F0FFFF",
    "Alice Blue": "#F0F8FF",
    "Ghost White": "#F8F8FF",
    "White Smoke": "#F5F5F5",
    "Sea Shell": "#FFF5EE",
    "Old Lace": "#FDF5E6",
    "Floral White": "#FFFAF0",
    "Ivory": "#FFFFF0",
    "Antique White": "#FAEBD7",
    "Linen": "#FAF0E6",
    "Lavender Blush": "#FFF0F5",
    "Misty Rose": "#FFE4E1",
    "Gray": "#808080",
    "Light Gray": "#D3D3D3",
    "Black": "#000000",
    "Gainsboro": "#DCDCDC",
    "Silver": "#C0C0C0",
    "Dark Gray": "#A9A9A9",
    "Dim Gray": "#696969",
    "Light Slate Gray": "#778899",
    "Slate Gray": "#708090",
    "Dark Slate Gray": "#2F4F4F"
}

patterns = [
  "solid",
  "graphic",
  "stripes",
  "gingham",
  "plaid",
  "herringbone",
  "paisley",
  "houndstooth",
  "diamond",
  "bandhni",
  "kalamkari",
  "patola",
  "dabu",
  "pochampilli",
  "indian temple",
  "leheriya",
  "buti",
  "natural",
  "geometric",
  "floral",
  "ditsy",
  "matelassé",
  "suzani",
  "chevron",
  "ikat",
  "animal",
  "polka dot",
  "pin dot",
  "checkered",
  "toile",
  "greek",
  "southwestern",
  "chinoiserie",
  "flamestitch",
  "jacobean",
  "abstract",
  "african",
  "airbrush",
  "basket weave",
  "batik",
  "bird's eye",
  "bull's eye",
  "bohemian",
  "brick network",
  "camouflage",
  "coin dot",
  "celtic knot",
  "chinoserie",
  "cloverleaf",
  "dotted swiss",
  "damask",
  "diagonal",
  "designer",
  "digital",
  "fleur de lis",
  "fret",
  "graphic",
  "hawaiian",
  "hexagonal",
  "half drop",
  "harlequin",
  "illusion",
  "landscape",
  "lattice",
  "network",
  "nursery",
  "ogee",
  "oriental",
  "patriotic",
  "palmette",
  "polka dot",
  "pin dot",
  "placement",
  "provencal",
  "quatrefoil",
  "retro",
  "scale",
  "scroll",
  "swirl",
  "sprig",
  "tartan",
  "toil de juoy",
  "trefoil",
  "trellis",
  "vintage",
  "vermicular",
  "water colour",
  "zig zag",
  "aztec",
  "navajo",
  "kilm",
  "suzaani",
  "tribal"
]

materials = [
  "Cotton",
  "Canvas",
  "Jacquard",
  "Cork",
  "Lycra",
  "Neoprene",
  "Satin",
  "Silk",
  "Denim",
  "Leather",
  "Knitted",
  "Wool",
  "Fleece",
  "Fur",
  "Lace",
  "Linen",
  "Synthetic",
  "Velvet",
  "Cashmere",
  "Crepe",
  "Hemp",
  "Snakeskin",
  "Gatorskin",
  "Nylon",
  "Wood",
  "Horn",
  "Rubber",
  "Raffia"
]

categories = {
  "shoe": {
    "sneakers": [
        "dress sneakers",
        "hitops",
        "lace up",
        "slip on",
        "trainers",
        "skateboarding",
    ],
    "boots": [
        "chelsea",
        "chukka",
        "service",
        "desert",
        "dress",
        "ankle",
        "knee-high",
        "over-the-knee",
        "combat",
        "rain",
        "cowboy",
        "gladiator",
        "lita",
        "wellington",
        "martin",
    ],
    "formal": [],
    "derby": [],
    "blucher": [],
    "longwings": [],
    "wingtips": [],
    "full brogue": [],
    "half brogue": [],
    "quarter brogue": [],
    "monk strap": [],
    "double monk strap": [],
    "boat shoes": [],
    "moccasins": [
        "camp moccasins",
        "blucher moccasins",
    ],
    "wholecuts": [
        "medallion",
    ],
    "cap toe bals": [],
    "perf toe bals": [],
    "espadrilles": [],
    "plimsolls": [],
    "work": [],
    "slip ons": [],
    "clogs": [],
    "mules": [],
    "athletic": [],
    "boots": [

    ],
    "flats": [
        "ballerina",
        "mary jane",
        "fantasy",
        "juttis",
    ],
    "espadrilles": [],
    "outdoor": [],
    "oxfords": [],
    "heels": [
        "pumps",
        "wedges",
        "platform",
        "kitten",
        "ankle strap",
        "doll",
        "mary jane",
        "stiletto",
        "block",
        "cone",
        "slingback",
        "cork",
        "spool",
        "peep-toe",
        "scarpin",
        "espadrilles",
    ],
    "sandals": [
        "slip ons",
        "gladiator",
        "flip-flops",
        "huarache",
        "jelly",
        "open toe",
    ],
    "dance": [
        "ballet flats",
        "pointe",
        "ballroom dancing",
        "athletic dancing",
        "character",
        "tap",
        "jazz",
        "foot thongs",
    ],
    "slippers": [],
    "loafers": [
        "penny",
        "slipper",
        "tassel",
    ],
    "d'orsay": [],
    "mules": [
        "loafer",
        "high heel",
        "bootie",
        "clog",
    ]
  },
  "top": {
    "shirts": [
        "t shirt",
        "blouse",
        "button down",
        "halter top",
        "knit",
        "polo",
        "tunic",
        "turtle neck",
        "wrap",
        "bodysuit",
        "camisole",
        "tank top",
        "button front",
        "dress shirt",
        "hawaiian",
        "henley",
        "tank top",
        "t shirt",
        "turtle neck",
        "polo",
        "sports jersey",
        "rugby jersey",
        "sweat shirt",
        "sweat shirt pullover",
        "athletic",
        "track jacket",
        "long sleeve",
        "short sleeve",
    ],
    "hoodies": [
        "zip-up",
        "pullover",
        "fitted",
        "athletic",
        "knit",
        "baja",
        "designer",
        "sleeveless",
        "fleece",
        "flannel button up",
        "zip-up",
        "pullover",
        "fitted",
        "athletic",
        "knit",
        "baja",
        "designer",
        "sleeveless",
        "fleece",
        "button up cardigan",
        "tunic style",
    ],
    "sweaters": [
        "cardigan",
        "crewneck",
        "full zip",
        "polo",
        "turtle neck",
        "vest",
        "v-neck",
        "cardigan",
        "collared",
        "cowl_neck",
        "crewneck",
        "full_zip",
        "henley",
        "hooded",
        "poncho",
        "scoop_neck",
        "shrug",
        "sweater_coat",
        "tunic",
        "v_neck",
        "wrap",
        "mock_sweaters",
        "turtle_neck",
        "sleeveless",
        "vest",
    ],
    "coats & jackets": [
        "fleece",
        "bomber",
        "jean",
        "military",
        "motorcycle",
        "parka",
        "peacoat",
        "poncho",
        "puffer",
        "rainwear",
        "trench",
        "varsity",
        "vest",
        "windbreaker",
        "wool",
        "cape",
        "fleece",
        "jean",
        "military",
        "motorcycle",
        "parka",
        "peacoat",
        "poncho",
        "puffer",
        "raincoat",
        "trench",
        "vest",
        "windbreaker",
        "wool",
    ],
    "blazers & sport coats": [
        "double breasted",
        "four button",
        "one button",
        "three button",
        "two button",
    ],
  },
  "bottom": {
    "jeans": [
        "baggy",
        "boot cut",
        "cargo",
        "carpenter",
        "straight leg",
        "overalls",
        "relaxed",
        "skinny",
        "slim",
        "regular",
        "relaxed",
        "loose fit",
        "mom",
        "boyfriend",
        "girlfriend",
        "skinny",
        "pencil",
        "bootcut",
        "wide_leg",
        "baggy",
        "jeggings",
        "cargo",
        "bell bottoms",
        "flared",
        "overalls",
        "straight",
        "capri",
        "cropped",
        "slim",
        "cigarette",
        "tapered",
        "trouser",
        "jogger",
        "paper bag",
        "sailor",
        "ripped",
        "distressed",
        "crocheted",
        "laced",
        "patched",
        "side-slit",
    ],
    "pants": [
        "cargo",
        "carpenter",
        "casual",
        "corduroys",
        "dress flat",
        "dress pleated",
        "khakies",
        "chinos",
        "sweat pants",
        "baggy",
        "bell bottoms",
        "culottes",
        "fatigue trousers",
        "harem pants",
        "hot pants",
        "jodhpurs",
        "leggings",
        "palazzo",
        "pegged",
        "trousers",
        "sailor",
        "straight",
        "stirrup",
        "stove pipe",
        "toreador",
        "cargo",
        "casual",
        "corduroys",
        "dress",
        "khakis",
        "chinos",
        "leather",
        "linen",
        "capri",
        "cropped",
    ],
    "shorts": [
        "athletic",
        "board",
        "cargo",
        "carpenter",
        "casual",
        "corduroys",
        "jean",
        "dress",
        "khakis",
        "chinos",
        "bermuda",
        "bike",
        "cargo",
        "chino",
        "khaki",
        "jean",
        "high_waisted",
        "pull_on",
        "short",
        "skort",
    ],
    "swimwear": [
        "board shorts",
        "trunks",
    ],
    "skirts": [
        "a-line",
        "asymmetrical",
        "box pleat",
        "bubble",
        "circular",
        "cowl",
        "gathered",
        "godet",
        "gored",
        "handkerchief",
        "high/low",
        "high waisted",
        "mermaid/fishtail",
        "miniskirt",
        "pencil",
        "full",
        "peplum",
        "pleated",
        "sarong",
        "tiered",
        "layered",
        "ruffle",
        "tulip",
        "wrap",
        "yoke",
        "maxi",
        "peasant",
        "straight",
    ]
  },
  "one_piece": {
    "suits": [
        "double breasted",
        "four button",
        "one button",
        "three button",
        "two button",
        "tuxedo"
    ],
    "dresses": [
        "a-line",
        "apron",
        "asymmetrical",
        "baby doll",
        "ballgown",
        "balloon",
        "blazer dress",
        "blouson",
        "boho",
        "camisole",
        "cocktail",
        "corset",
        "denim",
        "empire waisted",
        "fit and flare",
        "halter neck",
        "handkerchief",
        "kaftan",
        "kimono",
        "lace",
        "long sleeve",
        "drop waist",
        "mermaid",
        "mini",
        "midi",
        "maxi",
        "over the shoulder",
        "one shoulder",
        "peasant",
        "pencil",
        "peplum",
        "pinafore",
        "pouffe sleeve",
        "princess gown",
        "qipao",
        "sari",
        "sheath",
        "shift",
        "shirt dress",
        "skater",
        "slip",
        "smock",
        "strapless",
        "sundress",
        "sweater",
        "t-shirt",
        "tea length",
        "tent",
        "tube",
        "tutu",
        "wrap",
        "yole",
        "knee length",
        "high low",
    ],
    "jumpsuit": [],
    "romper": [],
    "suits": [
        "blazer",
        "dress",
        "pant",
        "skirt",
    ],
    "swimwear": [
        "one_piece",
        "two_piece",
        "cover_up",
        "beach_accessory"
    ]
  },
  "accessory": {
    "belts": [
        "casual",
        "klink",
        "leather",
        "dress",
        "suede",
        "seatbelt",
        "canvas web",
        "buckle",
        "horseshoe buckle",
        "cummerbund",
        "military",
        "chain",
        "hip",
        "yoke",
        "cinch",
        "jeweled",
        "studded",
        "rhinestone",
        "lace-up",
        "sash",
        "obi",
        "braided",
        "twist",
        "bow",
        "garter suspender",
        "peplum",
        "d-ring",
        "skinny knot",
        "thin"
    ],
    "hats": [
        "baseball",
        "snapback",
        "dad",
        "trucker",
        "sport",
        "visor",
        "water sport",
        "mariner",
        "newsboy",
        "pork pie",
        "beanie",
        "bucket",
        "trapper",
        "turban",
        "flat",
        "ascot",
        "beret",
        "military",
        "boonie",
        "safari",
        "fedora",
        "trilby",
        "derby",
        "panama",
        "boater",
        "gambler",
        "gatsby",
        "cowboy",
        "sun hat",
        "victorian",
        "bowler",
        "straw",
        "floppy",
        "witch",
        "cocktail",
        "deerstalker",
        "breton",
        "pillbox",
        "bonnet",
        "cartwheel",
        "cloche",
        "kettle brim"
    ],
    "glasses": [
        "prescription",
        "sunglasses",
        "aviator",
        "browline",
        "brow-bar",
        "wayfarer",
        "square",
        "round",
        "geometric",
        "keyhole",
        "rimless",
        "semi-rimless",
        "wrap-around",
        "sport",
        "shield",
        "biker",
        "clip-on",
        "retro",
        "oversized",
        "cat-eye",
        "clout goggles",
        "hater blockers"
    ],
    "formal": [
        "tie",
        "collar stays",
        "hankerchief"
    ],
    "bags": [
        "backpack",
        "tote",
        "barrel",
        "briefcase",
        "gym",
        "hobo",
        "cross-body",
        "satchel",
        "messenger",
        "sling",
        "laptop",
        "beach",
        "cinch",
        "portfolio",
        "camera bag",
        "clutch",
        "shoulder",
        "handbag",
        "crossbody",
        "bowler",
        "envelope",
        "minaudière",
        "baguette",
        "wristlet",
        "round",
        "duffel",
        "doctor's",
        "muff",
        "basket",
        "backpack purse",
        "weekender",
        "cosmetic",
        "waist",
        "fanny pack",
        "belt",
        "bucket"
    ],
    "other": [
        "bandana",
        "gloves",
        "scarf",
        "umbrella",
        "wallet",
        "wrap",
        "fascinator",
        "headband",
        "hijab",
        "cardholder"
    ],
    "jewelry": [
        "necklaces",
        "earrings",
        "tie bar",
        "cufflinks",
        "watch",
        "ring",
        "necklace",
        "bracelet",
        "ankle bracelet",
        "pins"
    ],
    "hair": [
        "barrettes",
        "bandeau headband",
        "sweatband",
        "wrap",
        "hair clip",
        "hair pins",
        "hair bands",
        "hair comb",
        "hair stick",
        "scrunchie",
        "ribbon",
        "side comb",
        "tiara",
        "flower tiara",
        "bun shaper",
        "bun wrap",
        "crown shaper",
        "chain halo"
    ],
  }
}