//https://omjclothing.com/blogs/blog/17243569-patterns-101
//https://sewguide.com/fabric-patterns/

const patterns = [
  //common mens
  "stripes",
  "hairline stripes",
  "dress stripes",
  "candy stripes",
  "pin stripes",

  "gingham",
  "plaid",
  "herringbone",
  "paisley",
  "houndstooth",
  "diamonds",

  // indian
  "bandhni",
  "kalamkari",
  "patola",
  "dabu",
  "pochampilli",
  "indian temple",
  "leheriya",
  "buti",

  "natural",
  "geometric",
  "floral",
  "ditsy",
  "matelassé",
  "suzani",
  "chevron",
  "ikat",
  "animal",
  "polka dot",
  "pin dot",
  "checkered",
  "toile",
  "greek",
  "southwestern",
  "chinoiserie",
  "flamestitch",
  "jacobean",
  "abstract",
  "african",
  "airbrush",
  "basket weave",
  "batik",
  "bird’s eye",
  "bull’s eye",
  "bohemian",
  "brick network",
  "camouflage",
  "coin dot",
  "celtic knot",
  "chinoserie",
  "cloverleaf",
  "dotted swiss",
  "damask",
  "diagonal",
  "designer",
  "diamond",
  "digital",
  "fleur de lis",
  "fret",
  "graphic",
  "hawaiian",
  "hexagonal",
  "half drop",
  "harlequin",
  "illusion",
  "landscape",
  "lattice",
  "metallese",
  "network",
  "nursery",
  "ogee",
  "oriental",
  "patriotic",
  "palmette",
  "polka dot",
  "pin dot",
  "placement",
  "provencal",
  "quatrefoil",
  "retro",
  "scale",
  "scroll",
  "swirl",
  "sprig",
  "tartan",
  "toil de juoy",
  "trefoil",
  "trellis",
  "vintage",
  "vermicular",
  "water colour",
  "zig zag",
  "aztec",
  "navajo",
  "kilm",
  "suzaani",
  "tribal",
];
export default patterns;
