const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const clothingSlots = [
  "head", //hats, hair clips
  "eyes", //glasses, sunglasses
  "left_ear", //earrings
  "right_ear",
  "face", //masks
  "neck", //necklaces
  "top", //tops
  "left_arm",
  "right_arm",
  "left_wrist", //watches, bracelets
  "right_wrist",
  "left_hand", //gloves?
  "right_hand",
  // should do all fingers
  "left_index_finger", //rings
  "waist", //pants, belt
  "hips", //pants, belt
  "legs", //pants, shorts
  "left_ankle", //is ankle jewelry still a thing? socks
  "right_ankle",
  "left_foot", //socks, shoes/sandles/boots
  "right_foot",
];

const categories = {
  mens: {
    tops: {
      button_front: {},
      dress_shirt: {},
      hawaiian: {},
      henley: {},
      tank: {},
      t_shirt: {},
      turtle_neck: {},
      polo: {},
      jersey: {},
      rugby: {},
    },
    sweats: {
      sweat_shirt: {},
      sweat_shirt_pullover: {},
      sweat_pants: {},
      sweat_suit: {},
      track_jacket: {},
    },
    hoodies: {},
    sweaters: {
      cardigan: {},
      crewneck: {},
      full_zip: {},
      polo: {},
      turtle_neck: {},
      vest: {},
      v_neck: {},
    },
    jeans: {
      baggy: {},
      boot_cut: {},
      cargo: {},
      carpenter: {},
      straight_leg: {},
      overalls: {},
      relaxed: {},
      skinny: {},
      slim: {},
    },
    pants: {
      cargo: {},
      carpenter: {},
      casual: {},
      corduroys: {},
      dress_flat: {},
      dress_pleated: {},
      khakies: {},
      chinos: {},
    },
    shorts: {
      athletic: {},
      board: {},
      cargo: {},
      carpenter: {},
      casual: {},
      corduroys: {},
      jean: {},
      dress: {},
      khakis: {},
      chinos: {},
    },
    coats_jackets: {
      fleece: {},
      bomber: {},
      jean: {},
      military: {},
      motorcycle: {},
      parka: {},
      peacoat: {},
      poncho: {},
      puffer: {},
      rainwear: {},
      trench: {},
      varsity: {},
      vest: {},
      windbreaker: {},
      wool: {},
    },
    blazers_sport_coats: {
      double_breasted: {},
      four_button: {},
      one_button: {},
      three_button: {},
      two_button: {},
    },
    suits: {
      double_breasted: {},
      four_button: {},
      one_button: {},
      three_button: {},
      two_button: {},
      tuxedo: {},
    },
    athletic: {
      jacket: {},
      jersey: {},
      pants: {},
      shorts: {},
      polo: {},
      long_sleeve_shirt: {},
      short_sleeve_shirt: {},
      t_shirt: {},
      tank: {},
      hoodie: {},
      sweat_pants: {},
      sweat_shirt: {},
      track_pants: {},
      track_suit: {},
    },
    swim: {
      board: {},
      trunks: {},
    },
    accessories: {
      belt: {},
      hat: {},
      glasses: {
        prescription: {},
        sun: {},
      },
      tie: {},
      watch: {},
      wallet: {
        cardholder: {},
      },
      backpack: {},
      bag: {},
      briefcase: {},
      bandana: {},
      collar_stays: {},
      gloves: {},
      hankerchief: {},
      scarf: {},
      turban: {},
      umbrella: {},
    },
    shoes: {
      athletic: {},
      boots: {},
      sneakers: {},
      outdoor: {},
      oxfords: {},
      sandals: {},
      slippers: {},
      work: {},
      loafers: {},
      slip_ons: {},
      clogs: {},
      mules: {},
    },
    jewelry: {
      bracelet: {},
      cufflinks: {},
      earrings: {},
      necklaces: {},
      pins: {},
      rings: {},
    },
  },
  womens: {
    dress: {
      mini: {},
      knee_length: {},
      midi: {},
      maxi: {},
      high_low: {},
      jumpsuit: {},
      romper: {},
    },
    top: {
      blouse: {},
      button_down: {},
      halter: {},
      knit: {},
      polo: {},
      t_shirt: {},
      tunic: {},
      turtle_neck: {},
      wrap: {},
      bodysuit: {},
      camisole: {},
      tank: {},
    },
    sweater: {
      cardigan: {},
      collared: {},
      cowl_neck: {},
      crewneck: {},
      full_zip: {},
      henley: {},
      hooded: {},
      poncho: {},
      scoop_neck: {},
      shrug: {},
      sweater_coat: {},
      tunic: {},
      v_neck: {},
      wrap: {},
      mock_sweaters: {},
      turtle_neck: {},
      sleeveless: {},
      vest: {},
    },
    jeans: {
      boot_cut: {},
      boyfriend: {},
      cargo: {},
      flare: {},
      leggings: {},
      overalls: {},
      relaxed: {},
      straight: {},
      wide_leg: {},
      capri: {},
      cropped: {},
      skinny: {},
      slim: {},
    },
    pants: {
      cargo: {},
      casual: {},
      corduroys: {},
      dress: {},
      khakis: {},
      chinos: {},
      leather: {},
      linen: {},
      capri: {},
      cropped: {},
    },
    skirts: {
      a_line: {},
      asymmetrical: {},
      bubble: {},
      full: {},
      maxi: {},
      mini: {},
      peasant: {},
      pleated: {},
      straight: {},
      pencil: {},
      tiered: {},
      wrap: {},
    },
    coats_jackets: {
      cape: {},
      fleece: {},
      jean: {},
      military: {},
      motorcycle: {},
      parka: {},
      peacoat: {},
      poncho: {},
      puffer: {},
      raincoat: {},
      trench: {},
      vest: {},
      windbreaker: {},
      wool: {},
    },
    suit: {
      blazer: {},
      dress: {},
      pant: {},
      skirt: {},
    },
    athletic: {
      jacket: {},
      jersey: {},
      shorts: {},
      socks: {},
      sports_bra: {},
      vest: {},
      leggings: {},
      pants: {},
      tights: {},
      polos: {},
      t_shirt: {},
      tank: {},
      dress: {},
      skirt: {},
      skorts: {},
      hoodie: {},
      sweat_pants: {},
      sweat_shirt: {},
      sweat_suit: {},
      track_jacket: {},
      track_suit: {},
    },
    swim: {
      one_piece: {},
      two_piece: {},
      cover_up: {},
      beach_accessory: {},
    },
    accessories: {
      glasses: {
        prescription: {},
        sun: {},
      },
      handbag: {
        shoulder: {},
        tote: {},
        crossbody: {},
        satchel: {},
        hobo: {},
        backpack: {},
        cosmetic: {},
        waist: {},
        fanny_pack: {},
        messenger: {},
        bucket: {},
      },
      wallet: {},
      belt: {},
      hat: {},
      hair_accessory: {},
      watch: {},
      scarf: {},
      wrap: {},
      bandana: {},
      fascinator: {},
      gloves: {},
      headband: {},
      hijab: {},
      umbrella: {},
      cardholder: {},
    },
    jewelry: {
      ring: {
        finger: {},
        ear: {},
        nose: {},
        toe: {},
      },
      necklace: {},
      bracelet: {
        wrist: {},
        ankle: {},
      },
      pins: {},
    },
    shoes: {
      athletic: {},
      boots: {},
      sneakers: {},
      flats: {},
      outdoor: {},
      oxfords: {},
      heels: {
        stiletto: {},
        wedge: {},
        block: {},
        kitten: {},
        platform: {},
        cone: {},
      },
      sandals: {},
      slippers: {},
      work: {},
      loafers: {},
      slip_ons: {},
      clogs: {},
      mules: {},
    },
    shorts: {
      bermuda: {},
      bike: {},
      cargo: {},
      chino: {},
      khaki: {},
      jean: {},
      high_waisted: {},
      pull_on: {},
      short: {},
      skort: {},
    },
  },
};

const schema = new Schema({
  accessory: Boolean,
  slot: [String], //list of slots the item occupies/covers
  brand: String,
  size: { type: Schema.Types.ObjectId, ref: "Size" },
  colors: {
    primary: String,
    secondary: String,
    tertiary: String,
  },
  pattern: String,
  material: String,
  fit: String, //tight, well, loose
  category: { type: Schema.Types.ObjectId, ref: "Category" },
});

schema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: function (doc, ret) {
    // delete ret._id;
    // delete ret.hashedPassword;
  },
});

module.exports = mongoose.model("Item", schema);
